# -*- coding: utf-8 -*-
"""Rathnamma_Data science_week2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvzgbBXCczeLUvTMrTuy7al_vK8dUpcm
"""

# Task 1: Basic Operations
def basic_operations():

  # Accept two integer inputs from the user
    num1 = int(input("Enter the first number: "))
    num2 = int(input("Enter the second number: "))

  # Perform arithmetic operations
    addition = num1 + num2
    subtraction = num1 - num2
    multiplication = num1 * num2
    division = num1 / num2 if num2 != 0 else "Error: Division by zero"
    modulus = num1 % num2 if num2 != 0 else "Error: Modulus by zero"
    exponentiation = num1 ** num2

   # Print results using f-strings
    print(f"Addition: {num1} + {num2} = {addition}")
    print(f"Subtraction: {num1} - {num2} = {subtraction}")
    print(f"Multiplication: {num1} * {num2} = {multiplication}")
    print(f"Division: {num1} / {num2} = {division}")
    print(f"Modulus: {num1} % {num2} = {modulus}")
    print(f"Exponentiation: {num1} ** {num2} = {exponentiation}")

basic_operations()
print("\n")

# Task 2: Working with Lists and Arrays
import numpy as np

# Create a list
numbers = [12, 45, 7, 23, 56, 89, 34, 1, 6, 8]

# Print the length of the list
print(f"Length of the list: {len(numbers)}")

# Find the maximum and minimum value
print(f"Maximum value: {max(numbers)}")
print(f"Minimum value: {min(numbers)}")

# Add a new element to the list and remove one element
numbers.append(99)
numbers.remove(1)
print(f"Updated list: {numbers}")

# Sort the list
numbers.sort()
print(f"Ascending order: {numbers}")
numbers.sort(reverse=True)
print(f"Descending order: {numbers}")

# Convert the list into a NumPy array
np_array = np.array(numbers)

# calculate Mean, Median, and Standard Deviation
print(f"Mean: {np.mean(np_array)}")
print(f"Median: {np.median(np_array)}")
print(f"Standard Deviation: {np.std(np_array)}")
print("\n")

# Task 3: Dictionaries and Sets

# Create a dictionary named student
student = {
    "name": "John",
    "age": 20,
    "course": "Data Science",
    "marks": 85
}

# Print each key-value pair using a loop
for key, value in student.items():
    print(f"{key}: {value}")

# Add a new key called grade
student["grade"] = "A"
print(f"Updated student dictionary: {student}")

# Create a set
courses = {"Python", "Data Science", "AI", "Python"}
print(f"Unique courses: {courses}")

# Perform set operations
set1 = {"Python", "Data Science", "AI"}
set2 = {"AI", "Machine Learning", "Deep Learning"}
print(f"Union: {set1 | set2}")
print(f"Intersection: {set1 & set2}")
print(f"Difference (set1 - set2): {set1 - set2}")
print("\n")

# Task 4: File Handling

# Create a text file named student_data.txt
with open("student_data.txt", "w") as file:
    file.write("Name,Course,Marks\n")
    file.write("John,Data Science,80\n")
    file.write("Alice,Python,90\n")
    file.write("Bob,AI,70\n")
    file.write("Charlie,Machine Learning,85\n")
    file.write("David,Deep Learning,75\n")

# Read the file and display students with marks > 75
with open("student_data.txt", "r") as file:
    for line in file.readlines()[1:]:
        Name, course, marks = line.strip().split(",")
        if int(marks) > 75:
            print(f"Name: {Name}, Course: {course}, Marks: {marks}")