# -*- coding: utf-8 -*-
"""Rathnamma_Data_science _week 3_ Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XnU0xChy8gyvRMCEI2k60DWGgudmQsVw
"""

# a)import Library and uploading Data set

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
df=pd.read_csv('/content/Amazon Sales Anaylsis.csv')
df.head()

#b) Performing Data cleaning

# get Data set info

print(df.info())

print(df.describe())

# checking null values

print(df.isnull().sum())

#getting data types of  each column

print(df.dtypes)

# dropping  duplicates permanently

df.drop_duplicates(inplace=True)

#Boxplot to visualize distribution &  outliers

sns.boxplot(x=df['quantity_sold'])
plt.title('quantity_sold distribution')
plt.show()

# c)Data manipulation

# calculating profit margin

df['profit margin']=df['profit']/df['total_revenue']
print(df.head())

# filtering data based on  product category

df_filtered=df[df['product_category']=='Electronics']
print(df_filtered.head())

# Grouping data based on product category and profit

df_grouped=df.groupby('product_category')['profit'].sum()
print(df_grouped)

# d) Data Visualization

# Bar plot based on product category and quantity sold

sns.barplot(x='product_category',y='quantity_sold',hue='rating',data=df_filtered)
plt.title('Electronics revenue')
plt.xlabel('product_category')
plt.ylabel('total_revenue')
plt.xticks(rotation=45)
plt.show()

df.plot(kind='bar',x='product_category',y='quantity_sold')
plt.title('product quantity sold')
plt.show()

# Pie chart based on product category and quantity sold

df.groupby('product_category')['quantity_sold'].sum().plot(kind='pie',autopct='%1.1f%%')
plt.title('sales by  category')
plt.show()

#Scatter plot based on price and profit

plt.scatter(df['quantity_sold'],df['profit'])
plt.xlabel('quantity_sold')
plt.ylabel('profit')
plt.title('quantity_sold vs profit')
plt.show()

# e) Feature Engineering

#Creating new feature

df['revenue']=df['quantity_sold']*df['price']
print(df.head())

df['discounted_price']=df['price']*0.9
print(df.head())

#Data Agreegation and sorting

print(df.groupby('product_category')['quantity_sold'].sum().sort_values(ascending=False))